# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: orangc
fates = [
    "You and {target} are best friends.",
    "You and {target} are man and wife.",
    "{target} is your archnemesis!",
    "You and {target} are simple acquaintances.",
    "You and {target} are siblings.",
    "You and {target} have never met.",
    "You and {target} tolerate each other.",
    "You and {target} are sworn rivals.",
    "You and {target} are inseparable.",
    "You and {target} are business partners.",
    "You and {target} are childhood friends.",
    "You and {target} are gym buddies.",
    "You and {target} are gaming buddies.",
    "You and {target} are travel companions.",
    "You and {target} are mortal enemies.",
    "You and {target} can't stand each other.",
    "You and {target} constantly argue.",
    "You and {target} have an awkward history.",
    "You and {target} have unresolved beef.",
    "You and {target} are on good terms.",
    "You and {target} are complete strangers.",
    "You and {target} share a single brain cell.",
    "You and {target} have matching personalities.",
    "You and {target} have absolutely nothing in common.",
    "You and {target} are secretly plotting something.",
    "You and {target} would survive the apocalypse together.",
    "You and {target} are partners in crime.",
    "You and {target} would never trust each other.",
    "You and {target} trust each other with your lives.",
    "You and {target} communicate entirely through memes.",
    "You and {target} have a love-hate relationship.",
]
